backend:
  name: github
  repo: DiNitride/PortfolioSite
media_folder: static/assets
public_folder: assets
collections:
  - name: project
    label: Projects
    label_singular: Project
    folder: project
    create: true
    fields:
      - { name: title, label: Name }
      - { name: type, label: Type }
      - { name: weight, label: Weight, widget: number, default: 5 }
      - { name: technologies, label: Technologies}
      - { name: linkString, label: Link Text}
      - { name: link, label: Link}
      - { name: description, label: Description}
  - name: posts
    label: Posts
    label_singular: Post
    folder: post
    create: true
    fields:
      - { name: title, label: Name }
      - { name: date, label: Date, widget: datetime, timeFormat: false }
      - { name: content, label: Content, widget: markdown}