backend:
  name: github
  repo: DiNitride/PortfolioSite
media_folder: static/assets
public_folder: assets
collections:
  - name: project
    label: Project
    folder: project
    create: true
    fields:
      - { name: title, label: Name }
      - { name: type, label: Type }
      - { name: weight, label: Weight, widget: number, default: 5 }
      - { name: technologies, label: Technologies}
      - { name: linkString, label: Link Text}
      - { name: link, label: Link}
      - { name: description, label: Description}